version:  '3'

services:
  server:
    build: ./server/
    ports:
      - "8080:8080"
  client:
    build: ./client/
    ports:
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080/
  