version:  '3'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver

  server:
    build: ./server/
    ports:
      - "8080:8080"
    environment:
      - REQUEST_NAME_OTEL=get-temp-zipcode-server-request
      - OTEL_SERVICE_NAME=get-temp-zipcode-server
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector

  client:
    build: ./client/
    ports:
      - "8081:8081"
    depends_on:
      - server
      - jaeger-all-in-one
      - prometheus
      - otel-collector
    environment:
      - SERVER_URL=http://server:8080/
      - REQUEST_NAME_OTEL=get-temp-zipcode-client-request
      - OTEL_SERVICE_NAME=get-temp-zipcode-client
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317